# SITE SETTINGS
title: Wild Track
description: Discover animal tracking data for research and conservation.
url: "https://animal-tracking.hp.gbif-staging.org/"
baseurl: "" # Start with slash if used

# SOCIAL PROFILES
email: info@gbif.org
github_username: bio-logging

# THEME SETTINGS
algae:
  rootLang: en
  # logo: /assets/images/fungi.svg # Displayed with 28px height
  # logoAndTitle: false
  archive_permalink: /news/
  latestPostLimit: 2
  style:
    square: false
    # colors: see _main.scss
    coloredHeadlineLinks: false
useSharedLibrary: true # Use the new component library
updateTranslationMenuOnWidgetEvents: true
permalink: pretty # Will strip extensions like .html from urls

# BUILD SETTINGS
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: gbif/jekyll-hp-base-theme
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .LICENSE
  - .netlify.toml
  - .README.md
  - serve.json

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: "" # All files in the project
    values:
      layout: "page"
      lang: en
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: "/news/:year/:slug/"
